/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smict.struts.data.checklogin;
import com.smict.struts.data.retrivedata;
import com.smict.struts.form.IndexForm;
import com.smict.struts.form.MainForm;

import java.sql.*;
import java.util.*;

/** 
 * MyEclipse Struts
 * Creation date: 04-22-2015
 * 
 * XDoclet definition:
 * @struts.action path="/index" name="indexForm" input="index.jsp" scope="request" validate="true"
 */
public class IndexAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		IndexForm indexForm = (IndexForm) form;// TODO Auto-generated method stub
		
		String forwardText = "";

		String user = indexForm.getUser();
		String pass = indexForm.getPass();
		String beforelogin = indexForm.getBeforelogin();
		String name = indexForm.getName(),lastname=indexForm.getLastname(),address=indexForm.getAddress();
		String submit = indexForm.getBtnsubmit(),submit1 = indexForm.getBtnsubmit1();
		
		if (submit != null){
			String showuser = user;
			String showpass = pass;
			indexForm.reset(mapping, request);
			//indexForm.setShowuser(showuser);
			//indexForm.setShowpass(showpass);
			MainForm mf =new MainForm();
			checklogin chklogin = new checklogin();
			try {
				indexForm = chklogin.chklogin(showuser, showpass);
				mf = chklogin.chklogin1(showuser, showpass);
				if(indexForm.isIstrue()){
					/*name = indexForm.getName();
					mf.setUsername(indexForm.getUser());
					indexForm.setUser(indexForm.getUser());
					indexForm.setName(name);*/
					//indexForm.setUser(indexForm.getUser());
					//pass = indexForm.getPass();
					//indexForm.setPass(indexForm.getPass());
					//name = indexForm.getName();
					//lastname=indexForm.getLastname();
					//indexForm.setName(indexForm.getName());
					//indexForm.setLastname(indexForm.getLastname());
					//indexForm.setAddress(indexForm.getAddress());
					request.setAttribute("user", indexForm.getName());
					request.setAttribute("MainForm",mf);
					forwardText="success";
				}
				else{
					forwardText="false";
					indexForm.reset(mapping, request);
				}
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}
		if(submit1 != null){
			//String usern = (String) 
			request.getAttribute("user");
			//String user_name = usern;
			//request.setAttribute("user_name", user_name);
			forwardText = "false";
		}
		if(beforelogin != null){
			checklogin chklogin = new checklogin();
			try {
				indexForm = chklogin.chklogin(user, pass);
				HttpSession session = request.getSession();
				session.setAttribute("username", indexForm.getUser());
				session.setAttribute("pass", indexForm.getPass());
				session.setAttribute("name",indexForm.getName());
				session.setAttribute("lastname", indexForm.getLastname());
				session.setAttribute("address", indexForm.getAddress());
				forwardText = "afterlogin";
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		return mapping.findForward(forwardText);
	}
}