/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.smict.struts.form.MainForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-23-2015
 * 
 * XDoclet definition:
 * @struts.action path="/main" name="mainForm" input="/form/main.jsp" scope="request" validate="true"
 */
public class MainAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
	//	MainForm mainForm = (MainForm) form;// TODO Auto-generated method stub
		
		MainForm mf = new MainForm();
		//String username = mainForm.getUsername();
		//String show_user = mainForm.getUsername();
		//request.setAttribute("showuser", mainForm.getUsername());
		mf = (MainForm) request.getAttribute("MainForm");
	//	mf.setUsername();
		String username = mf.getUsername();
		mf.setName(username);
		request.setAttribute("showuser", username);
		//request.setAttribute("username", username);
		
		String forwardtext = "success";
		return mapping.findForward(forwardtext);
	}
}