/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-22-2015
 * 
 * XDoclet definition:
 * @struts.form name="indexForm"
 */
public class IndexForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** tb3 property */
	private String tb3;

	/** tb2 property */
	private String tb2;

	/** tb1 property */
	private String tb1;
	private String tb4;
	private String tb5;
	private String user,pass,showuser,showpass,btnsubmit;
	private String name,lastname,address,btnsubmit1,beforelogin;
	private boolean istrue;
	

	/*
	 * Generated Methods
	 */
	public IndexForm(){};
	public IndexForm(String username, String password, String name,
			String lastname, String address) {
		super();
		this.tb1 = username;
		this.tb2 = password;
		this.tb3 = name;
		this.tb4 = lastname;
		this.tb5 = address;
		// TODO Auto-generated constructor stub
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		this.user="";
		this.pass="";
		this.name="";
		this.lastname="";
		this.address="";
		this.setIstrue(false);
		this.showuser="";
		this.showpass="";
	}

	/** 
	 * Returns the tb3.
	 * @return String
	 */
	public String getTb3() {
		return tb3;
	}

	/** 
	 * Set the tb3.
	 * @param tb3 The tb3 to set
	 */
	public void setTb3(String tb3) {
		this.tb3 = tb3;
	}

	/** 
	 * Returns the tb2.
	 * @return String
	 */
	public String getTb2() {
		return tb2;
	}

	/** 
	 * Set the tb2.
	 * @param tb2 The tb2 to set
	 */
	public void setTb2(String tb2) {
		this.tb2 = tb2;
	}

	/** 
	 * Returns the tb1.
	 * @return String
	 */
	public String getTb1() {
		return tb1;
	}

	/** 
	 * Set the tb1.
	 * @param tb1 The tb1 to set
	 */
	public void setTb1(String tb1) {
		this.tb1 = tb1;
	}

	public String getTb4() {
		return tb4;
	}

	public void setTb4(String tb4) {
		this.tb4 = tb4;
	}

	public String getTb5() {
		return tb5;
	}

	public void setTb5(String tb5) {
		this.tb5 = tb5;
	}
	public String getUser() {
		return user;
	}
	public void setUser(String user) {
		this.user = user;
	}
	public String getPass() {
		return pass;
	}
	public void setPass(String pass) {
		this.pass = pass;
	}
	public String getShowuser() {
		return showuser;
	}
	public void setShowuser(String showuser) {
		this.showuser = showuser;
	}
	public String getShowpass() {
		return showpass;
	}
	public void setShowpass(String showpass) {
		this.showpass = showpass;
	}
	public String getBtnsubmit() {
		return btnsubmit;
	}
	public void setBtnsubmit(String btnsubmit) {
		this.btnsubmit = btnsubmit;
	}
	public boolean isIstrue() {
		return istrue;
	}
	public void setIstrue(boolean istrue) {
		this.istrue = istrue;
	}
	public void setName(String name) {
		// TODO Auto-generated method stub
		this.name = name;
	}
	public void setLastname(String lastname) {
		// TODO Auto-generated method stub
		this.lastname = lastname;
	}
	public void setAddress(String address) {
		// TODO Auto-generated method stub
		this.address = address;
	}
	public String getName() {
		return name;
	}
	public String getLastname() {
		return lastname;
	}
	public String getAddress() {
		return address;
	}
	public String getBtnsubmit1() {
		return btnsubmit1;
	}
	public void setBtnsubmit1(String btnsubmit1) {
		this.btnsubmit1 = btnsubmit1;
	}
	public String getBeforelogin() {
		return beforelogin;
	}
	public void setBeforelogin(String beforelogin) {
		this.beforelogin = beforelogin;
	}
}